version: '3.8'

services:
  db:
    image: postgres:15
    container_name: marketing_db
    restart: always
    environment:
      POSTGRES_USER: marketing_user
      POSTGRES_PASSWORD: marketing_password
      POSTGRES_DB: marketing_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
